version: '2'

services:

  ftp:
    image: webdevops/vsftp
    environment:
      FTP_USER: thisisme
      FTP_PASSWORD: thisismypass
    volumes:
      - "./ftp:/data/ftp"

  gutils:
    image: gutils
    environment:
      GUTILS_ASCII_DIRECTORY: /ascii
      GUTILS_BINARY_DIRECTORY: /binary
      GUTILS_CONFIG_DIRECTORY: /config
      GUTILS_NETCDF_DIRECTORY: /netcdf
      GUTILS_FTP_URL: ftp
      GUTILS_FTP_USER: thisisme
      GUTILS_FTP_PASS: thisismypass
      RUN_BINARY_WATCH: "yes"
      RUN_ASCII_WATCH: "yes"
      RUN_NETCDF_WATCH: "yes"
    volumes:
      - "./binary:/binary"
      - "./ascii:/ascii"
      - "./netcdf:/netcdf"
      - "./config:/config:ro"
    depends_on:
      - ftp
