version: '2'

services:

  ftp:
    image: webdevops/vsftp
    environment:
      FTP_USER: thisisme
      FTP_PASSWORD: thisismypass
    volumes:
      - "./run/ftp:/data/ftp"

  gutils:
    image: gutils
    environment:
      GUTILS_FTP_URL: ftp
      GUTILS_FTP_USER: thisisme
      GUTILS_FTP_PASS: thisismypass
      RUN_BINARY_TO_ASCII_WATCH: "yes"
      RUN_ASCII_TO_NETCDF_WATCH: "yes"
      #RUN_NETCDF_TO_FTP_WATCH: "yes"
      RUN_NETCDF_TO_ERDDAP_WATCH: "yes"
      GUTILS_NETCDF_TEMPLATE: ioos_ngdac
    volumes:
      - "./run/binary:/gutils/binary"
      - "./run/ascii:/gutils/ascii"
      - "./run/netcdf:/gutils/netcdf"
      - "./run/config:/gutils/config:ro"
      - "./run/erddap/content:/gutils/erddap/content"
      - "./run/erddap/flag:/gutils/erddap/flag"
    depends_on:
      - ftp

  browse:
    image: nginx:stable
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./run/binary:/gutils/binary:ro"
      - "./run/ascii:/gutils/ascii:ro"
      - "./run/netcdf:/gutils/netcdf:ro"
      - "./run/config:/gutils/config:ro"
    ports:
      - "20000:80"

  erddap:
    image: axiom/docker-erddap
    volumes:
      - "./run/erddap/content/datasets.xml:/usr/local/tomcat/content/erddap/datasets.xml"
      - "./run/erddap/flag:/erddapData/flag"
      - "./run/netcdf:/gutils/netcdf:ro"
    ports:
      - "8080:8080"

  # download:
  #   image: sgs-content
  #   volumes:
  #     - ./run/binary:/data/secoora/dev/binary
  #     - ./run/config:/data/secoora/dev/config
  #   command: /bin/bash -c "sleep 30; secoora_download.sh"
  #   depends_on:
  #     - erddap
