version: '2'

services:

  ftp:
    image: webdevops/vsftp
    environment:
      FTP_USER: thisisme
      FTP_PASSWORD: thisismypass
    volumes:
      - "./ftp:/home"

  gutils:
    image: gutils
    environment:
      GUTILS_FTP_URL: ftp
      GUTILS_FTP_USER: thisisme
      GUTILS_FTP_PASS: thisismypass
      RUN_BINARY_TO_ASCII_WATCH: "yes"
      RUN_ASCII_TO_NETCDF_WATCH: "yes"
      RUN_NETCDF_TO_FTP_WATCH: "yes"
      RUN_NETCDF_TO_ERDDAP_WATCH: "yes"
    volumes:
      - "./binary:/gutils/binary"
      - "./ascii:/gutils/ascii"
      - "./netcdf:/gutils/netcdf"
      - "./config:/gutils/config:ro"
      - "./erddap/content:/gutils/erddap/content"
      - "./erddap/flag:/gutils/erddap/flag"
    depends_on:
      - ftp

  browse:
    image: nginx:stable
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./binary:/gutils/binary:ro"
      - "./ascii:/gutils/ascii:ro"
      - "./netcdf:/gutils/netcdf:ro"
      - "./config:/gutils/config:ro"
    ports:
      - "20000:80"

  erddap:
    image: axiom/docker-erddap
    volumes:
      - "./erddap/content/datasets.xml:/usr/local/tomcat/content/erddap/datasets.xml"
      - "./erddap/flag:/erddapData/flag"
      - "./netcdf:/gutils/netcdf:ro"
    ports:
      - "8080:8080"
    depends_on:
      - gutils

  download:
    image: sgs-content
    volumes:
      - ./binary:/data/secoora/dev/binary
      - ./config:/data/secoora/dev/config
    command: /bin/bash -c "sleep 30; secoora_download.sh"
    depends_on:
      - erddap
