package:
    name: gutils
    version: "1.0.0"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - gbdr
        - gsw
        - numpy
        - scipy

test:
    imports:
        - gutils
        - gutils.ctd
        - gutils.gps
        - gutils.yo

about:
    home: https://github.com/axiom-data-science/GUTILS
    license: MIT License
    summary: 'A set of Python utilities for post processing glider data'
