package:
    name: gutils
    version: "1.2.6"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - cc-plugin-glider >=1.0.4
        - compliance-checker
        - gsw <3.1.0
        - netcdf4
        - numpy
        - pandas
        - pocean-core >=1.2.0
        - python
        - scipy
        - six
        - whichcraft
test:
    imports:
        - gutils
        - gutils.ctd
        - gutils.yo
        - gutils.filters
        - gutils.nc
        - gutils.slocum

    commands:
        - gutils_create_nc --help
        - gutils_check_nc --help

about:
    home: https://github.com/SECOORA/GUTILS
    license: MIT License
    license_file: LICENSE
    summary: A set of Python utilities for reading, merging, and post processing Teledyne Webb Slocum Glider data
