package:
    name: gutils
    version: "2.1.0"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - gutils_create_nc = gutils.nc:main_create
        - gutils_check_nc = gutils.nc:main_check
        - gutils_binary_to_ascii_watch = gutils.watch.binary:main_to_ascii
        - gutils_ascii_to_netcdf_watch = gutils.watch.ascii:main_to_netcdf
        - gutils_netcdf_to_ftp_watch = gutils.watch.netcdf:main_to_ftp
        - gutils_netcdf_to_erddap_watch = gutils.watch.netcdf:main_to_erddap

requirements:
    build:
        - python
        - setuptools
    run:
        - cc-plugin-glider >=1.0.4
        - compliance-checker
        - gsw <3.1.0
        - netcdf4
        - numpy
        - pandas
        - pocean-core >=1.2.1
        - pyinotify
        - python
        - scipy
        - six
        - whichcraft
test:
    imports:
        - gutils
        - gutils.ctd
        - gutils.yo
        - gutils.filters
        - gutils.nc
        - gutils.slocum

    commands:
        - gutils_create_nc --help
        - gutils_check_nc --help
        - gutils_binary_to_ascii_watch --help
        - gutils_ascii_to_netcdf_watch --help
        - gutils_netcdf_to_ftp_watch --help
        - gutils_netcdf_to_erddap_watch --help

about:
    home: https://github.com/SECOORA/GUTILS
    license: MIT License
    license_file: LICENSE
    summary: A set of Python utilities for reading, merging, and post processing Teledyne Webb Slocum Glider data
